package estudando; // NOME DO PACOTE.

//ÁREA DE IMPORTAÇÃO DE OUTROS PACOTES.

public class Classe {//CHAVE QUE INDICA O INCIO DO ESCOPO DA CLASSE.
    
    //ESSA É A ESTRUTURA DE UMA CLASSE JAVA.
    //AQUI É O BLOCO DA CLASSE, OU SEJA, É O LOCAL NO QUAL VOCÊ IRÁ CRIAR AS CARACTERÍSTICAS E AÇÕES DOS SEUS OBJETOS.
    //AQUI VOCÊ PODE CRIAR VARIÁVEIS.
    int idade;
    //VOCÊ TAMBÉM PODE CRIAR SEUS MÉTODOS.
    public void exibeIdade(){
        System.out.println(idade);
    }
    //Obs: O NOME DA CLASSE SEMPRE DEVE TER SUA PRIMEIRA LETRA MAIUSCULA.
    //E CASO O NOME SEJA COMPOSTA POR OUTRAS PALAVRAS, CADA PALAVRA DEVE TER SUA PRIMEIRA LETRA MAIUSCULA.
    //EXEMPLO.
    
    //MinhaPrimeiraClasse.
    
    //E ESSA SÃO ALGUMAS DAS CARACTERISTICAS DE UMA CLASSE.
}//CHAVE QUE INDICA O FIM DO ESCOPO DA CLASSE.
